#! /usr/bin/env ruby
# -*- ruby -*-

PATH = ENV['PATH'] = [
  File.expand_path(File.join(__dir__, 'internal')),
  ENV['PATH']
].join(':')

PROGRAM = File.basename($PROGRAM_NAME)

abort unless (COMMAND = ARGV.shift)

exec({ 'PATH' => PATH }, "#{PROGRAM}.#{COMMAND}", *ARGV)
